spring.application.name=application

# ── Connexion ─────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true&prepareThreshold=0
spring.datasource.username=postgres.oaailqafowxjoixbharf
spring.datasource.password=${DB_PASSWORD}

# Désactiver les prepared statements (obligatoire avec PgBouncer)
spring.datasource.hikari.connection-init-sql=SET statement_timeout=30000

spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true


# ✅ Port 7860 imposé par Hugging Face
server.port=${PORT:7860}



# ── Hibernate / JPA ────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.type.descriptor.sql=TRACE

# ── JWT Configuration ───────────────────────────────────────
app.security.jwt.secret=${JWT_SECRET}  # Utilise une variable d'environnement ou une valeur par défaut
app.security.jwt.access-token-expiration-ms=${JWT_EXPIRATION}
app.security.jwt.refresh-token-expiration-ms=604800000



# ── Logging ───────────────────────────────────────────────

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=TRACE
#logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=TRACE
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=ERROR
logging.level.com.upf.backend.application.security=DEBUG
logging.level.org.springframework.security=DEBUG

# Configuration pour les mails 
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Configurer le service de mail (exemple avec Brevo)
brevo.api.key=${BREVO_API_KEY}
app.mail.from=${BREVO_SENDER_EMAIL}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

supabase.url=${SUPABASE_URL}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
# Taille max des fichiers uploadés
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Désactiver les prepared statements côté JDBC
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# Désactiver côté Hibernate aussi

spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true
