spring.application.name=application

# ── Connexion ─────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true
spring.datasource.username=postgres.oaailqafowxjoixbharf
spring.datasource.password=${DB_PASSWORD}

# Désactiver les prepared statements (obligatoire avec PgBouncer)
spring.datasource.hikari.connection-init-sql=SET statement_timeout=30000

spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true


# ✅ Port 7860 imposé par Hugging Face
server.port=${PORT:7860}



# ── Hibernate / JPA ────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ── JWT Configuration ───────────────────────────────────────
app.security.jwt.secret=${JWT_SECRET}  # Utilise une variable d'environnement ou une valeur par défaut
app.security.jwt.access-token-expiration-ms=${JWT_EXPIRATION}
app.security.jwt.refresh-token-expiration-ms=604800000



# ── Logging ───────────────────────────────────────────────

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=TRACE
#logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=TRACE
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=ERROR

# Configuration pour les mails 
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Configurer le service de mail (exemple avec Brevo)

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true